export const ActionTypes = {
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_STUFF: "ADD_STUFF",
  CONNECT: "CONNECT",
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
  ADD_CHARACTERS: "ADD_CHARACTERS",
  FETCH_ROOMS: "FETCH_ROOMS"
}
